###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/6416dc2fbae97286bdcbb8b4

###
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title" : "Ford v Ferrari",
    "year" : 2019,
    "director" : "James Mangold",
    "language":"English",
    "IMDb_rating":"8.1"
}


###
DELETE http://localhost:3000/movies/


###
PATCH http://localhost:3000/movies/
Content-Type: application/json

{
    "title" : "Ford v Ferrari",
    "year" : 2019,
    "director" : "James Mangold",
    "language":"English",
    "IMDb_rating":"8.1"
}
